param(
    [string]$OutputRoot = "G:\HackathonDay\fixtures\ingestion"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Reset-Directory {
    param([string]$Path)

    if (Test-Path -LiteralPath $Path) {
        Remove-Item -LiteralPath $Path -Recurse -Force
    }

    New-Item -ItemType Directory -Path $Path | Out-Null
}

function Write-TextFile {
    param(
        [string]$Path,
        [string]$Content
    )

    $directory = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $directory)) {
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
    }

    Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8
}

Add-Type -AssemblyName System.IO.Compression.FileSystem

$stagingRoot = Join-Path $OutputRoot "_staging"
Reset-Directory -Path $OutputRoot
New-Item -ItemType Directory -Path $stagingRoot | Out-Null

try {
    $validRoot = Join-Path $stagingRoot "valid-archive"
    New-Item -ItemType Directory -Path $validRoot | Out-Null
    Write-TextFile -Path (Join-Path $validRoot "package.json") -Content @'
{
  "name": "fixture-valid-archive",
  "version": "1.0.0",
  "packageManager": "pnpm@9.0.0"
}
'@
    Write-TextFile -Path (Join-Path $validRoot ".github\workflows\ci.yml") -Content @'
name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
'@
    Write-TextFile -Path (Join-Path $validRoot "services\api\pom.xml") -Content @'
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>fixture</groupId>
  <artifactId>api</artifactId>
  <version>1.0.0</version>
</project>
'@
    [System.IO.Compression.ZipFile]::CreateFromDirectory(
        $validRoot,
        (Join-Path $OutputRoot "valid-archive.zip")
    )

    $nestedRoot = Join-Path $stagingRoot "nested-repos"
    New-Item -ItemType Directory -Path $nestedRoot | Out-Null
    Write-TextFile -Path (Join-Path $nestedRoot "README.md") -Content "nested repo fixture"
    Write-TextFile -Path (Join-Path $nestedRoot "services\web\package.json") -Content @'
{
  "name": "fixture-web",
  "version": "1.0.0"
}
'@
    Write-TextFile -Path (Join-Path $nestedRoot "services\worker\requirements.txt") -Content @'
fastapi==0.115.0
uvicorn==0.30.6
'@
    Write-TextFile -Path (Join-Path $nestedRoot "libs\java-lib\build.gradle") -Content @'
plugins {
    id 'java'
}

group = 'fixture'
version = '1.0.0'
'@
    [System.IO.Compression.ZipFile]::CreateFromDirectory(
        $nestedRoot,
        (Join-Path $OutputRoot "nested-repos.zip")
    )

    $corruptPath = Join-Path $OutputRoot "corrupt-archive.zip"
    Set-Content -LiteralPath $corruptPath -Value "this is not a real zip archive" -Encoding UTF8

    $oversizedPath = Join-Path $OutputRoot "oversized-upload.bin"
    $buffer = New-Object byte[] (6MB)
    [System.IO.File]::WriteAllBytes($oversizedPath, $buffer)

    Write-TextFile -Path (Join-Path $OutputRoot "README.md") -Content @'
# Worker 2 Ingestion Fixtures

Fixtures generated by `scripts/generate-worker2-fixtures.ps1`.

- `valid-archive.zip`: well-formed archive with mixed ecosystem hints.
- `nested-repos.zip`: archive containing nested repositories for recursion tests.
- `corrupt-archive.zip`: invalid archive payload with a `.zip` extension.
- `oversized-upload.bin`: synthetic payload intended to exceed small upload-size limits in tests.
'@
}
finally {
    if (Test-Path -LiteralPath $stagingRoot) {
        Remove-Item -LiteralPath $stagingRoot -Recurse -Force
    }
}
